[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "python311Packages.venv" # ✅ Add this to include the venv module
]

[phases.build]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]
