[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.build]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]
