order_defaults:  # order basic
  exchange: "NFO"  # NSE Derivative Segment
  producttype: "INTRADAY"  # Bracket Order only supports INTRADAY
  duration: "DAY"
  ordertype: "LIMIT"   # LIMIT or MARKET

websocket:
  mode: full
  correlation_id: "sub_001"
  subscriptions:
    - exchange_type: 1
      tokens: ["7", "14366"]

data_source:
  type: yaml
  path: data/strategies.yaml