common:  # order basic
    exchange: "NFO"  # NSE Derivative Segment
    producttype: "INTRADAY"  # Bracket Order only supports INTRADAY
    duration: "DAY"
    ordertype: "LIMIT"   # LIMIT or MARKET

websocket:
  mode: full
  correlation_id: "sub_001"
  subscriptions:
    - "26000"

limit_orders:
  - tradingsymbol: "RELIANCE-EQ"
    symbol_token: "26000"
    quantity: 1
    price: 95.0
